# Copyright 2024 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Some CI tests run on our GitLab servers due to licenses and tools
name: verilator-ci
on: [push, pull_request, workflow_dispatch]
jobs:
  verilator-ci:
    name: Public Verilator CI
    runs-on: ubuntu-latest
    container:
      image: fconti/pulp-verilator:latest
    steps:
      - name: Test
        # Skip on forks or pull requests from forks due to missing secrets.
        if:
          github.repository == 'pulp-platform/pulpissimo' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        run: echo "HELLO"
