# Copyright 2024 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Some CI tests run on our GitLab servers due to licenses and tools
name: verilator-ci
on: [push, pull_request, workflow_dispatch]
jobs:
  verilator-ci:
    name: Public Verilator CI
    runs-on: ubuntu-22.04
    container:
      image: fconti/pulp-verilator:latest
      volumes: 
        - ${{ github.workspace }}:/workspaces
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check container environment
        run: |
          echo "Running on:"
          cat /etc/os-release
      - name: Where am I?
        shell: bash
        run: |
          cd /workspaces
          echo `ls -l`
      - name: Verilate
        shell: bash
        run: |
          cd /workspaces
          make checkout
          make verilate
      - name: SW sanity check
        shell: bash
        env:
          VERILATOR_PATH: /workspaces/build/verilator
        run: |
          cd /workspaces
          git submodule update --init --recursive
          source sw/pulp-runtime/configs/pulpissimo.sh
          cd sw/regression_tests/hello
          make clean all run platform=verilator bootmode=fast_debug
